name: Generate Portainer Templates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at 00:00 UTC

permissions:
  contents: write

jobs:
  generate-templates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate templates
      run: |
        python portainer_templates_generate.py -o releases/templates.json
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add releases/templates.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update templates.json"
          if [ "${{ github.event_name }}" == "push" ]; then
            git push origin HEAD:${{ github.ref }}
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            git push origin HEAD:${{ github.head_ref }}
          fi
        fi
